project:
  type: website
  output-dir: docs

website:
  description: "Some notes and musics"
  site-url: https://spulick.github.io # you must change this appropriately for RSS feeds to work properly
  title: spulick
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
      center:
          - text: "Copyright Sreehari Pulickamadhom Sreedhar. All rights reserved."
  navbar:
    right:
      - file: about.qmd
        text: About Me
      - icon: rss
        href: index.xml

execute:
    # freeze computations instead of re-executing them each time
    freeze: auto

format:
    html:
        theme:
            - cosmo
            - style.scss
        mainfont: "EB Garamond, Georgia, serif"
        monofont: Fira Code, consolas, courier, monospace
        highlight-style: github

        html-math-method:
            method: mathjax
            url: "https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.4/tex-mml-chtml.js"
        include-in-header:
            text: |
                <style>
                @import url('https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap')
                @import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap')
                </style>
                <script>
                MathJax = {
                    tex: {
                        tags: 'all'  // should be 'ams', 'none', or 'all'
                    },
                    output: {
                        font: 'mathjax-fira'
                    }
                };
                </script>
        
        # Provides a navigation menu for the content on the page
        toc: true
        toc-location: right-body
        
        # number sections like a latex article
        number-sections: true
        number-depth: 3
        shift-heading-level-by: 1

        anchor-sections: true

        # provide code copy button
        code-copy: true

        # show qmd source
        code-tools: false

        link-external-icon: true
        link-external-newwindow: true

        lang: en

        # remove html comments from source
        strip-comments: true