project:
  type: website
  output-dir: docs

website:
  description: "Some notes and musics"
  site-url: https://orectique.github.io # you must change this appropriately for RSS feeds to work properly
  title: spulick
  navbar:
    right:
      - about.qmd

format:
  html:
    theme:
      - litera
      - lux
    css: styles.css



